defmodule AshDiscord.Resource.Info do
  @moduledoc """
  Introspection functions for AshDiscord.Resource extension.

  This module provides functions to query Discord event handling configuration
  on resources that use the AshDiscord.Resource extension.

  All functions are generated by `Spark.InfoGenerator` and provide access to
  configuration defined in the `ash_discord do` block.

  ## Examples

      iex> AshDiscord.Resource.Info.discord_entity(MyApp.Message)
      {:ok, :message}

      iex> AshDiscord.Resource.Info.discord_events(MyApp.Message)
      {:ok, %{
        MESSAGE_CREATE: :from_discord,
        MESSAGE_UPDATE: :from_discord,
        MESSAGE_DELETE: :destroy
      }}

      iex> AshDiscord.Resource.Info.discord_event_action(MyApp.Message, :MESSAGE_CREATE)
      {:ok, :from_discord}
  """

  use Spark.InfoGenerator,
    extension: AshDiscord.Resource,
    sections: [:ash_discord]

  @doc """
  Returns the Discord entity type configured for this resource, if any.

  ## Examples

      iex> AshDiscord.Resource.Info.discord_entity(MyApp.Message)
      {:ok, :message}

      iex> AshDiscord.Resource.Info.discord_entity(MyApp.ActivityLogger)
      :error  # No entity type, uses explicit events
  """
  @spec discord_entity(Spark.Dsl.t() | map()) :: {:ok, atom()} | :error
  def discord_entity(resource) do
    case Spark.Dsl.Extension.get_opt(resource, [:ash_discord], :discord_entity, nil) do
      nil -> :error
      entity_type -> {:ok, entity_type}
    end
  end

  @doc """
  Returns the complete Discord event→action map for this resource.

  This includes both entity defaults and explicit event mappings.

  ## Examples

      iex> AshDiscord.Resource.Info.discord_events(MyApp.Message)
      {:ok, %{
        MESSAGE_CREATE: :from_discord,
        MESSAGE_UPDATE: :from_discord,
        MESSAGE_DELETE: :destroy,
        MESSAGE_DELETE_BULK: :destroy
      }}
  """
  @spec discord_events(Spark.Dsl.t() | map()) :: {:ok, %{atom() => atom()}} | :error
  def discord_events(resource) do
    case Spark.Dsl.Extension.get_persisted(resource, :ash_discord_events) do
      nil -> :error
      event_map when map_size(event_map) == 0 -> :error
      event_map -> {:ok, event_map}
    end
  end

  @doc """
  Returns the action name for a specific Discord event, if configured.

  ## Examples

      iex> AshDiscord.Resource.Info.discord_event_action(MyApp.Message, :MESSAGE_CREATE)
      {:ok, :from_discord}

      iex> AshDiscord.Resource.Info.discord_event_action(MyApp.Message, :UNKNOWN_EVENT)
      :error
  """
  @spec discord_event_action(Spark.Dsl.t() | map(), atom()) :: {:ok, atom()} | :error
  def discord_event_action(resource, event) do
    case discord_events(resource) do
      {:ok, event_map} ->
        case Map.fetch(event_map, event) do
          {:ok, action} -> {:ok, action}
          :error -> :error
        end

      :error ->
        :error
    end
  end

  @doc """
  Returns true if the resource has the AshDiscord.Resource extension.

  ## Examples

      iex> AshDiscord.Resource.Info.ash_discord_resource?(MyApp.Message)
      true

      iex> AshDiscord.Resource.Info.ash_discord_resource?(MyApp.RegularResource)
      false
  """
  @spec ash_discord_resource?(Spark.Dsl.t() | map()) :: boolean()
  def ash_discord_resource?(resource) do
    AshDiscord.Resource in Spark.extensions(resource)
  end
end
