name: Local CI (Act Optimized)

on:
  workflow_dispatch: # Manual trigger only for local development

concurrency:
  group: ci-local-${{ github.ref }}
  cancel-in-progress: true

jobs:
  local-ci:
    name: Local CI Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17"
          otp-version: "27"

      - name: Install dependencies
        run: |
          mix deps.get
          mix compile

      - name: Run quality checks
        run: |
          mix format --check-formatted
          mix credo --strict
          mix sobelow --config

      - name: Run tests
        run: mix test --warnings-as-errors
